### ISSUE TITLE
webpack2 tree-shaking 研究

### ISSUE THREAD

**Issue by jschyz** [webpack-china/awesome-webpack-cn#4]
里面包含一些常见的知识点，以及误区

### 简述
webpack 2 与 rollup 的 tree-shaking 的实现都是因为 ES6 module 的静态特性才得以实现。

webpack 2 默认是支持 tree-shaking，但由于现有的 production 环境，不得不使用 babel 语法转换器，在配置 .babelrc 时，跟 webpack 1 还是有所差别。

此项目只是对 webpack tree-shaking 技术的验证实验。

### 结论
- webpack 2 默认是支持 tree-shaking

- babel 配置没做特殊处理，是无法实现 tree shaking

- transform-es2015-modules-commonjs 插件影响 tree shaking 的实现

- 通过UglifyJs简单的代码压缩，过滤掉无用 DCE(无用代码消除)

- 只有es6模块才能使用webpack2做静态依赖解析

仓库地址：
https://github.com/Jschyz/webpack-tree-shaking

**Comment by lcxfs1991** [comment]
感谢贡献，已收录！
